# Generated by Django 5.1.4 on 2025-03-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusStop',
        ),
        migrations.DeleteModel(
            name='FamousSpots',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Malls',
        ),
        migrations.DeleteModel(
            name='Park',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Supermarket',
        ),
    ]
