# Generated by Django 5.1.4 on 2025-03-06 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0002_delete_busstop_delete_famousspots_delete_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('hostels', 'HOSTELS'), ('rooms', 'ROOMS'), ('pg', 'PG')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='nestf.reg_form')),
            ],
        ),
        migrations.CreateModel(
            name='NearestPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('hospital', 'Hospital'), ('supermarket', 'Supermarket'), ('bus_stop', 'Bus Stop'), ('restaurant', 'Restaurant'), ('park', 'Park'), ('famous_spots', 'Famous Spots')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearest_places', to='nestf.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nestf.product')),
            ],
        ),
    ]
