# Generated by Django 5.1 on 2025-03-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0003_product_nearestplace_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist_users',
            field=models.ManyToManyField(blank=True, related_name='wishlist_rooms', to='nestf.reg_form'),
        ),
    ]
