# Generated by Django 5.1 on 2025-03-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0004_product_wishlist_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlist_users',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestf.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestf.reg_form')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
