# Generated by Django 5.1 on 2025-03-10 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0005_remove_product_wishlist_users_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestf.product')),
            ],
            options={
                'unique_together': {('session_key', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
