# Generated by Django 5.1 on 2025-03-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0006_anonymouswishlist_delete_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anonymouswishlist',
            unique_together={('session_key', 'product')},
        ),
        migrations.AddField(
            model_name='anonymouswishlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nestf.reg_form'),
        ),
        migrations.AlterUniqueTogether(
            name='anonymouswishlist',
            unique_together={('session_key', 'product'), ('user', 'product')},
        ),
    ]
