# Generated by Django 5.1 on 2025-03-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0007_alter_anonymouswishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='nestf.feature'),
        ),
    ]
