# Generated by Django 5.1 on 2025-03-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0008_feature_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
