# Generated by Django 5.1 on 2025-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0009_feature_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='daily_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weekly_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
