# Generated by Django 5.1 on 2025-04-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0010_product_daily_price_product_weekly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='daily_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weekly_price',
        ),
    ]
