# Generated by Django 5.1 on 2025-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestf', '0011_remove_product_daily_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='daily_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weekly_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
